baseurl = "http://giurgiu.io/"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Alex Giurgiu"
title = "giurgiu.io"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "The personal website of Alex Giurgiu"
copyright = "Copyright © 2019 Alex Giurgiu"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
lang = "en"
github = "nustiueudinastea"
email = "alex@giurgiu.io"
linkedin = "alexgiurgiu"
twitter = "nustiudinastea"
social_banner = "img/banner.png"
posts_navigation = true
